adminUser:
  password: vault:pr-641-18arc/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-641-18arc/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:pr-641-18arc/prow:hmacToken
segmentWriteKey: vault:pr-641-18arc:segmentWriteKey
